name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1 — Checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2 — Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3 — Build da imagem
      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-festmedeiros-2025:latest .

      # 4 — Push da imagem
      - name: Push da imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-festmedeiros-2025:latest
